server:
  port: 8082

app:
  kafka:
    topic: demo-topic
    group: demo-group

spring:
  applicatoin:
    name: kafka-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${app.kafka.group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: "*"
